opennars/opennars

nars_lab/nars/lab/language/language_knowledge.nal
=> better NLP with "connectors"(and)

nars_core/nars/control/ConceptProcessing.java, nars_core/nars/entity/Sentence.java, nars_core/nars/entity/Task.java, nars_core/nars/inference/StructuralRules.java, nars_core/nars/language/CompoundTerm.java, nars_core/nars/language/Term.java
used IDEA Inspector for this. Could make things a bit faster as a side effect.
=> core : rewrite of manual array copy to bulk op

nars_core/nars/entity/Concept.java
=> core : Concept : less explicit (3)

src/main/java/nars/inference/RuleTables.java, src/main/java/nars/main/NAR.java, src/main/java/nars/main/Operators.java, src/main/java/nars/main/Plugins.java, src/main/java/nars/plugin/mental/InternalExperience.java, src/main/java/nars/plugin/perception/SensoryChannel.java, src/main/java/nars/plugin/perception/VisionChannel.java, src/main/java/nars/plugin/perception/VisualSpace.java
The first vision prototype, as it works it can safely go into master. Further developments will be added later as a separate pull request.
=> Vision, first prototype (reborn)

.travis.yml, README.md, src/test/java/nars/lab/ioutils/ExampleFileInput.java
=> ci(travis): added travis configuration. Fixed NPE in NALTest,

src/test/resources/nal/multi_step/nars_seqABC.nal, src/test/resources/nal/single_step/nal6.23.nal, src/test/resources/nal/single_step/nal6.24.nal, src/test/resources/nal/single_step/nal6.27.nal, src/test/resources/nal/single_step/nal9.0.nal, src/test/resources/nal/single_step/nal9.1.nal
… format was wrong in one, others are ignored for now.
=> Make tests succeed

src/main/java/org/opennars/control/ConceptProcessing.java
=> Revert "Refactoring ConceptProcessing"

CHANGELOG.md, pom.xml
=> build(versioning): bumping snapshot to 3.0.0

README.md
=> Updated requirements to java 8+ and jdk 10 recommended

pom.xml
More to follow once info provided
=> Update pom.xml with developers (TonyLo1)

CONTRIBUTING.md
=> docs(repo): contributing file now mentioned updating changelog

src/main/java/org/opennars/entity/TruthValue.java, src/main/java/org/opennars/storage/LevelBag.java
Just some simple transformations after reading some commits
=> Refactor: cleanup

src/main/java/org/opennars/control/ConceptProcessing.java
just two inversions of conditions
=>  Refactor ConceptProcessing.executeDecision()

src/main/java/org/opennars/inference/RuleTables.java
* asymmetricSymmetric()
* asymmetricAsymmetric()
=> Refactoring of TemporalRules.RuleTables (1)

src/main/java/org/opennars/inference/RuleTables.java
=> Refactor reason() into multiple methods (2)

src/main/java/org/opennars/control/DerivationContext.java, src/main/java/org/opennars/control/concept/ProcessQuestion.java, src/main/java/org/opennars/entity/Concept.java, src/main/java/org/opennars/entity/Sentence.java, src/main/java/org/opennars/inference/CompositionalRules.java, src/main/java/org/opennars/inference/RuleTables.java, src/main/java/org/opennars/inference/StructuralRules.java, src/main/java/org/opennars/language/CompoundTerm.java, src/main/java/org/opennars/language/Variables.java, src/main/java/org/opennars/main/Nar.java
Fixing some preconditions for inference rules, the parser etc., the system seems to run stable again. Next step after this PR will be to get rid of deep copies used for term sorting altogether.
=> System stable again PR

src/test/resources/nal/multi_step/long_term_stability.nal
Stability test addition of a stability integration test running for 2M inference steps that triggers most of the rules. The first one is a concatenation of the others, running for a long time.
=> Stability test1

src/main/java/org/opennars/inference/StructuralRules.java, src/main/java/org/opennars/language/CompoundTerm.java, src/test/java/org/opennars/core/ReplaceIntervalTest.java, src/test/resources/nal/single_step/nal8.5.4.nal, src/test/resources/nal/single_step/nal8_list.nal
making interval replacement for concept terms solid, and spatial sequences also.
=> Major stability improvement

src/main/java/org/opennars/inference/StructuralRules.java
* examples for one more complex case
* small refactoring
=> Docs: StructuralRules.transformProductImage()

src/main/java/org/opennars/inference/SyllogisticRules.java, src/main/java/org/opennars/main/Nar.java, src/main/java/org/opennars/main/Plugins.java, src/main/java/org/opennars/plugin/Plugin.java, src/main/java/org/opennars/plugin/perception/SensoryChannel.java, src/main/java/org/opennars/plugin/perception/VisionChannel.java, src/main/java/org/opennars/plugin/perception/VisualSpace.java, src/test/resources/nal/application/vision.nal
Vision updates, already nicely working prototype with example in nars_lab.
=> Vision pr1

src/main/java/org/opennars/inference/UtilityFunctions.java
Is a small deoptimization, improves unittest code coverage
=> removed unnecessary specialization

src/main/java/org/opennars/control/DerivationContext.java, src/main/java/org/opennars/control/TemporalInferenceControl.java, src/main/java/org/opennars/control/concept/ProcessAnticipation.java, src/main/java/org/opennars/control/concept/ProcessGoal.java, src/main/java/org/opennars/entity/Task.java, src/main/java/org/opennars/inference/CompositionalRules.java, src/main/java/org/opennars/inference/TemporalRules.java, src/main/java/org/opennars/inference/package-info.java, src/main/java/org/opennars/io/Narsese.java, src/main/java/org/opennars/io/package-info.java, src/main/java/org/opennars/language/package-info.java, src/main/java/org/opennars/main/Nar.java, src/main/java/org/opennars/operator/FunctionOperator.java, src/main/java/org/opennars/operator/mental/Anticipate.java, src/main/java/org/opennars/operator/mental/Believe.java, src/main/java/org/opennars/operator/mental/Evaluate.java, src/main/java/org/opennars/operator/mental/Feel.java, src/main/java/org/opennars/operator/mental/Name.java, src/main/java/org/opennars/operator/mental/Want.java, src/main/java/org/opennars/operator/mental/Wonder.java, src/main/java/org/opennars/plugin/mental/Abbreviation.java, src/main/java/org/opennars/plugin/mental/Counting.java, src/main/java/org/opennars/plugin/mental/Emotions.java, src/main/java/org/opennars/plugin/mental/InternalExperience.java, src/main/java/org/opennars/plugin/perception/VisionChannel.java, src/main/java/org/opennars/storage/Memory.java, src/main/java/org/opennars/storage/package-info.java, src/test/java/org/opennars/core/LongTermStability.java
Cleanup task construction etc.
=> Refactor: Task: Cleanup construction.

src/test/java/org/opennars/core/LongTermStability.java
=> Long Term Stability Test (2)

src/main/config/defaultConfig.xml, src/main/java/org/opennars/io/ConfigReader.java
Useful to read the parameters from a file
=> ConfigReader

src/main/config/defaultConfig.xml, src/main/java/org/opennars/io/ConfigReader.java, src/main/java/org/opennars/main/Nar.java, src/main/java/org/opennars/main/Shell.java, src/test/java/org/opennars/core/ApplySubstituteTest.java, src/test/java/org/opennars/core/AttentionTest.java, src/test/java/org/opennars/core/LongTermStability.java, src/test/java/org/opennars/core/NALTest.java, src/test/java/org/opennars/core/ReplaceIntervalTest.java, src/test/java/org/opennars/core/StabilityTest.java, src/test/java/org/opennars/core/TermTest.java, src/test/java/org/opennars/core/VariableTest.java, src/test/java/org/opennars/core/bag/BagOperationsTest.java, src/test/java/org/opennars/perf/BagPerf.java, src/test/java/org/opennars/perf/NALPerfLoop.java, src/test/java/org/opennars/perf/NALStressMeasure.java, src/test/java/org/opennars/util/test/TuneTuffy.java
* Nar Argument to pass in a XML file with the configuration
* Pulled all Plugins and Ops into the configuration
=> Configurable Nar ctor

.travis/deploy.sh
Reverts opennars/opennars#356
Didn't help so reverting
=> Revert "Update deploy.sh"

src/main/config/defaultConfig.xml, src/main/config/mvpConfig.xml, src/main/java/org/opennars/control/GeneralInferenceControl.java, src/main/java/org/opennars/control/TemporalInferenceControl.java, src/main/java/org/opennars/control/concept/ProcessGoal.java, src/main/java/org/opennars/entity/Concept.java, src/main/java/org/opennars/entity/Sentence.java, src/main/java/org/opennars/inference/LocalRules.java, src/main/java/org/opennars/inference/TemporalRules.java, src/main/java/org/opennars/inference/TruthFunctions.java, src/main/java/org/opennars/main/Nar.java, src/main/java/org/opennars/main/Parameters.java, src/main/java/org/opennars/operator/mental/FeelBusy.java, src/main/java/org/opennars/operator/mental/FeelSatisfied.java, src/main/java/org/opennars/operator/mental/Remind.java, src/main/java/org/opennars/operator/misc/Reflect.java, src/main/java/org/opennars/plugin/mental/Abbreviation.java, src/main/java/org/opennars/plugin/mental/Emotions.java, src/main/java/org/opennars/plugin/mental/InternalExperience.java, src/main/java/org/opennars/plugin/perception/VisionChannel.java, src/main/java/org/opennars/plugin/perception/VisualSpace.java, src/main/java/org/opennars/storage/Bag.java, src/main/java/org/opennars/storage/Memory.java, src/test/java/org/opennars/perf/BagPerf.java
Vision channel that should suffice for showing what we had in the paper (matrices, comparisons of matrices based on pixel data, learning of useful prototypes, their spatial relationships etc.), and can be optionally used, doesn't affect the reasoner core.
=> Update: Nar: Working vision prototype

src/main/java/org/opennars/main/Shell.java
And a few code changes + formating
=> Overhauled Shell

src/main/java/org/opennars/control/TemporalInferenceControl.java
rewrote list to single element
=> TemporalInferenceControl.addToSequenceTasks()

src/main/java/org/opennars/entity/Sentence.java, src/main/java/org/opennars/main/MiscFlags.java, src/main/java/org/opennars/main/Nar.java, src/main/java/org/opennars/operator/Operator.java, src/test/java/org/opennars/core/NALTest.java, src/test/java/org/opennars/core/StabilityTest.java
and betterconfigurable error handling.
=> Improve error handling

src/test/java/org/opennars/metrics/TemporalOneShotPseudoMetric.java
A simple metric to measure how good a Reasoner implementation is at one sot learning in a noisy environment.
=> Temporal Metric

src/test/java/org/opennars/metrics/AttentionMetric.java
* measures execution of goals, earlier get rewarded for more than later executions, better conf gets higher ranking
* exec scores are summed up for each test
* test is sampled a few times, average of tests is reported to the console
=> basic metric for attention for goal fullfillment

src/main/resources/unittest/TestscriptRetbool.sh, src/test/java/org/opennars/ops/TestSystemOperator.java
Tests if the call to the ^system op are done correctly.
Is not testing if the result is ok.
Test with the bash script moved into the root directory of the process. It is now in opennars-parent
>#!/bin/bash
>
>echo "true"
>exit 0 # success
=> Add: TestSystemOperator to test the ^system op

src/main/java/org/opennars/io/ConfigReader.java, src/main/resources/config/defaultConfig.xml, src/main/resources/config/mvpConfig.xml
Added default values for derived tasks' priority and durability. Added new logging to alert user if there are invalid fields in the config xml.
=> Added new default values and better logging
